### PR TITLE
Relax version restriction of Capybara

### PR DESCRIPTION
**Pull request by nertzy**
This gem seems to work just fine with Capybara 2.4

### CODE REVIEW

**Comment by bcardarella** [comment]
From what I recall Capybara isn't following SemVer so we cannot relax to the minor version.

**Comment by nertzy** [comment]
According to [Capybara's CONTRIBUTING.md](https://github.com/jnicklas/capybara/blob/3ae284460b1af35d40b077bf14f7222c2982c120/CONTRIBUTING.md) they try to follow SemVer.

Also in [this thread](https://github.com/jnicklas/capybara/issues/1334#issuecomment-46219477) (for example), the rspec-rails team decides to support "~> 2.2" instead of "~> 2.2.0" so I think we are safe to do so as well. The Capybara contributor in the thread, twalpole, states that 2.3.x and 2.4.x do not introduce any breaking changes.

**Comment by bcardarella** [comment]
SGTM

@michaeldupuisjr you want to cut a release with the patch version relaxed?

**Comment by michaeldupuisjr** [comment]
Closing via https://github.com/dockyard/capybara-extensions/pull/19

**Pull request closed without merging**
